#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 uralbash <root@uralbash.ru>
#
# Distributed under terms of the MIT license.

language: python

notifications:
  email: "sacrud@uralbash.ru"
  irc:
    channels:
      - "chat.freenode.net#sacrud"
    on_success: change
    on_failure: always

addons:
  postgresql: 9.4

python:
  - "2.7"

before_install:
  - sudo apt-get update -q

install:
  - sudo apt-get install -q fortune fortunes fortunes-ru
  - sudo apt-get install -q postgresql-contrib
  #- sudo apt-get install -q --yes --force-yes postgresql-common
  - sudo apt-get install -q postgresql-plpython-9.4
  - pip install nose coverage
  - pip install sqlalchemy pyramid
  - pip install psycopg2

  - pip install -r https://raw.githubusercontent.com/ITCase/pyramid_sacrud/develop/requirements.txt
  - pip install git+http://github.com/ITCase/pyramid_sacrud.git@develop

  - pip install git+http://github.com/ITCase/sqlalchemy_mptt.git
  - pip install git+http://github.com/ITCase/pyramid_sacrud_pages.git
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database sacrud;' -U postgres
  - psql -c "ALTER USER postgres with password 'secure-password';" -U postgres
  - python setup.py develop
  - initialize_example_db development_pg.ini
  - initialize_example_db development.ini

script:
  - "nosetests --cover-package=sacrud --cover-erase --with-coverage --with-doctest"
